package net.safik.bfx;

public enum BfxType {

	PROJECT,
	BLUEPRINT,PROCESS,
	FORM,FRAME,BOX,EVENT,
	ENTITY,FIELD,OPERATION,
	ACTION,FORMREF,ENTITYREF,EVENTREF,BOXREF,FIELDREF,VAR,VARREF,RULEREF,
	RULE,IF,ELSEIF,ELSE,WHERE,FOREACH, PROCESSREF

}
